version: '3'

services:
  postgres_db:
    image: registry.cn-hangzhou.aliyuncs.com/friedforks/postgres_db:v1
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: Hellochixiyu07!
      POSTGRES_DB: igibgo
    volumes:
      - /home/database/postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    networks:
      - igibgo_network

volumes:
  postgres-data:


networks:
  igibgo_network:
    external: true
