version: '3'

services:
  redis_db:
    image: redis:latest
    container_name: redis_db
    restart: always
    command: redis-server --requirepass Hellochixiyu07!
    volumes:
      - ./redis-data:/data
    ports:
      - "5002:6379"
    networks:
      - igibgo_network

volumes:
  redis-data:

networks:
  igibgo_network:
    external: true