spring:
  application:
    name: igibgo
  config:
    import: application-secrets.yaml
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: igibgo.cloud
      port: 5002
  datasource:
    #    url: jdbc:postgresql://igibgo.cloud:5000/igibgo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:postgresql://igibgo.cloud:5000/igibgo_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    port: 587
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

  jpa:
    open-in-view: true

server:
  port: 8000
  tomcat:
    max-swallow-size: -1

util:
    tmpDir: "/home/asdf/Downloads/tmpdir"
#  tmpDir: "C:/Users/Chixiyu/Downloads/tmpdir"


# deployment
#spring:
#  application:
#    name: igibgo
#  config:
#    import: application-secrets.yaml
#  data:
#    redis:
#      host: ${SPRING_REDIS_HOST:redis_db}
#      port: ${SPRING_REDIS_PORT:6379}
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres_db:5000/igibgo_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
#  mail:
#    host: smtp.qq.com
#    port: 587
#    properties.mail.smtp:
#      auth: true
#      starttls:
#        enable: true
#        required: true
#  servlet:
#    multipart:
#      max-file-size: 5GB
#      max-request-size: 5GB
#
#  jpa:
#    open-in-view: true
#
#server:
#  port: 8001
#  tomcat:
#    max-swallow-size: -1
#
#
#util:
#  tmpDir: "/tmpdir"
##  tmpDir: "C:/Users/Chixiyu/Downloads/tmpdir"